Feature/cplp 2843/add tenant url
eclipse-tractusx/portal-frontend pull request #100
Opened 2023-06-26 08:02 UTC by nidhigarg-bmw

## Description

Add edit and input field functionality to app subscription detail overlay

## Why

to update the tenant url into the table

## Issue

CPLP-2843

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-06-27 14:33 UTC, oyo requested changes
two things:
- rename one attribute
- it's best to update the shared component lib version to 2.0.4 (after the PR there has been merged)

2023-06-27 14:33 UTC, oyo commented on src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
> +          isValidate: (value: string) => isURL(value),
please rename this to `isValid` -> see my comment in the shared components PR

2023-06-28 05:40 UTC, jjeroch commented
@oyo  & @nidhigarg-bmw you can merge this pr, in case we get it finished till 09:30 am (1pm IST)

2023-06-28 07:15 UTC, oyo approved these changes

2023-06-28 07:16 UTC, merged