fix: Height related issue resolved
eclipse-tractusx/portal-frontend pull request #1001
Opened 2024-08-12 06:21 UTC by ss-nikunj

## Description

- Specifically, the footer section overlaps with the service content, and the content extends beyond the footer section.
- The footer section overlaps with the service details page's service context.

## Why

- Page content has a fixed height that is creating an issue for the footer, I have removed that height, and working perfectly fine for now.

## Issue

[Link to Github issue.
](https://github.com/eclipse-tractusx/portal-frontend/issues/995)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-12 07:53 UTC, evegufy requested changes
@ss-nikunj thanks for the contribution!
could you please make sure that your pr title aligns better with conventional commit messages? for instance `fix: resolve height related displaying issue` would be better

and just a friendly recommendation for future branches: this branch name is really long, it's good practice that keep them more concise and therefore shorter

2024-08-12 08:14 UTC, lavanya-bmw requested changes
Please update changelog file

2024-08-13 06:09 UTC, lavanya-bmw approved these changes
lgtm

2024-08-13 12:20 UTC, evegufy approved these changes

2024-08-13 12:21 UTC, merged