Feature/cplp 2856/use case
eclipse-tractusx/portal-frontend pull request #110
Opened 2023-06-29 13:04 UTC by nidhigarg-bmw

## Description

Add UseCase functionality

## Why

To display usecase

## Issue

[Link to Github issue.](https://jira.catena-x.net/browse/CPLP-2851)
[Link to Github issue.](https://jira.catena-x.net/browse/CPLP-2856)

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-06-29 19:03 UTC, evegufy requested changes
Contributing guidelines aren't followed: PR title and description need to be adjusted and improved. Also, links to Jira need to be removed in the PR description as this references to a closed system: if at all, mention the Jira issue ID

2023-06-30 06:21 UTC, evegufy requested changes
PR title still needs to be adjusted according contributing guidelines

2023-06-30 06:56 UTC, lavanya-bmw requested changes
Please remove console logs

2023-06-30 13:39 UTC, manojava-gk reviewed
Small finding

2023-06-30 13:39 UTC, manojava-gk commented on src/features/usecase/usecaseApiSlice.ts
> + * Copyright (c) 2021, 2023 BMW Group AG
remove company specific header

2023-07-03 08:09 UTC, lavanya-bmw approved these changes
lgtm

2023-07-03 08:53 UTC, oyo submitted a review, later dismissed

2023-07-03 08:58 UTC, evegufy approved these changes

2023-07-03 08:59 UTC, evegufy requested changes
please update the dependencies file:
https://github.com/eclipse-tractusx/portal-frontend/actions/runs/5442501820/jobs/9897815989?pr=110
download artifact and commit:
https://github.com/eclipse-tractusx/portal-frontend/actions/runs/5442501820?pr=110

2023-07-03 09:23 UTC, evegufy approved these changes

2023-07-03 09:25 UTC, merged