updates(home slider): slider button navigation
eclipse-tractusx/portal-frontend pull request #111
Opened 2023-06-30 05:37 UTC by manojava-gk

## Description

config buttons to navigate to a specific location

## Why

NA

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-06-30 06:52 UTC, lavanya-bmw requested changes
Please include changelog

2023-06-30 07:05 UTC, manojava-gk commented
> Please include changelog

No log info needed for this task

2023-06-30 07:07 UTC, lavanya-bmw approved these changes

2023-07-03 08:55 UTC, oyo approved these changes

2023-07-03 08:55 UTC, merged