fix: service marketplace active list --wip
eclipse-tractusx/portal-frontend pull request #1134
Opened 2024-09-20 15:40 UTC by Usmanfee

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-24 07:13 UTC, ss-nikunj reviewed
lgtm

2024-09-24 08:14 UTC, saadanzari approved these changes
looks fine to me. lgtm

2024-09-24 11:04 UTC, Usmanfee commented
@ma3u  @oyo  can you please review this PR ?
currently, I can't add you in this PR as reviewer. However, I have already created the ticket to become tractusx contributor: https://github.com/eclipse-tractusx/sig-infra/issues/547 . Thank you!

2024-10-09 11:54 UTC, evegufy reviewed
Hi @Usmanfee thank you for your contribution. Could you please update the DEPENDENCIES file? https://github.com/eclipse-tractusx/portal-frontend/actions/runs/10996801570?pr=1134

@oyo could you please review?

2024-10-09 14:12 UTC, Usmanfee commented
@evegufy  I have updated the dependency file but the error message still persists and not any clue with the error message. 
`signal need to update DEPENDENCIES`.

2024-10-10 07:30 UTC, manojava-gk reviewed
do not use hard coded string values

2024-10-10 07:30 UTC, manojava-gk commented on src/components/pages/ServiceMarketplace/index.tsx
> +  const [sortingType, setSortingType] = useState<string>('ReleaseDateDesc')
create an enum for this

2024-10-10 07:30 UTC, manojava-gk commented on src/components/pages/ServiceMarketplace/index.tsx
> +      setSortingType('ProviderDesc')
use enum

2024-10-10 08:46 UTC, Usmanfee commented
@manojava-gk  I have introduced enum for frequently used string for sorting type . can you have a look please ? :)

2024-10-10 08:59 UTC, manojava-gk commented
@Usmanfee Just to maintain consistency use PascalCase instead. See other examples in the page.

2024-10-10 09:56 UTC, Usmanfee commented
@manojava-gk  we are also use camelcase format in e.g. `PAGES` and `OVERLAYS` enum . I am using camelcase since this is the pattern backend support.

2024-10-10 10:03 UTC, manojava-gk commented
@Usmanfee one more thing, constants file is a place where we host most common things in the app. I do not think this sorting type is a generic one. it is very specific to the back end api. I prefer to define this in the specific api types's file.

In future we can define this in the constants when all apis sorting types are unified.

CC: @oyo

2024-10-11 08:23 UTC, Usmanfee commented
@manojava-gk  I have updated the code based on your suggestion. could you please have a look now ? Thank you :)

2024-10-15 05:58 UTC, manojava-gk commented
Looks fine now

2024-10-15 15:21 UTC, oyo requested changes
A few changes especially it's not a good pattern to handle undefined cases with an empty string. That was in the code before and went in unnoticed but now it would be a good occasion to clean that up.

2024-10-15 15:21 UTC, oyo commented on src/components/pages/ServiceMarketplace/index.tsx
> +    serviceType: ServiceTypeIdsEnum | ''
better use undefined instead of the empty string
`serviceType?: ServiceTypeIdsEnum`

2024-10-15 15:21 UTC, oyo commented on src/components/pages/ServiceMarketplace/index.tsx
> +  )
empty string -> undefined

2024-10-15 15:21 UTC, oyo commented on src/components/pages/ServiceMarketplace/index.tsx
> +    let serviceType: ServiceTypeIdsEnum | '' = ''
emtpy string -> undefined

2024-10-15 15:21 UTC, oyo commented on src/components/pages/ServiceMarketplace/index.tsx
> +      serviceType: serviceType ?? '',
empty string -> undefined

2024-10-15 15:21 UTC, oyo commented on src/features/serviceMarketplace/serviceApiSlice.ts
>              body.serviceType && serviceType
here we can set the empty string if serviceType is undefined

`(body.serviceType && serviceType) ?? ''`

2024-10-17 09:31 UTC, Usmanfee commented
@oyo  Thanks for your feedback :) . I have resolved your comments with suggested changes.

2024-10-23 09:53 UTC, evegufy commented on CHANGELOG.md
> +  - fixed service marketplace to display all active available servicesp[#1143](https://github.com/eclipse-tractusx/portal-frontend/issues/1143)
Hi @Usmanfee  we have an continuous issue in the changelog file, the entry is at the wrong place and it's not even shown as conflict. I suggest you revert any change to the changelog and add the information which should be added to the changelog in the PR description and I add it then at the next release to the changelog file, sorry for the inconvenience.

2024-10-24 06:57 UTC, oyo approved these changes

2024-10-24 13:22 UTC, Usmanfee commented
@evegufy  I have reverted changelog changes. @oyo  could you please re-approve and merge it again ? Thank you

2024-10-24 14:05 UTC, merged