fix: Fixed 400 issue when Clicking 'Load More' Button in Service Management
eclipse-tractusx/portal-frontend pull request #1175
Opened 2024-09-30 05:37 UTC by ss-nikunj

## Description
- In the Service Request Management section, clicking the 'Load More' button generates a 400 Bad Request error, preventing additional service requests from being loaded.

- A 400 Bad Request error is generated when attempting to load more service requests.
## Issue
- Github Issue: https://github.com/eclipse-tractusx/portal-frontend/issues/1168

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

![image](https://github.com/user-attachments/assets/41127f50-f74b-431d-a911-268c41f63beb)

2024-09-30 06:18 UTC, shubhamv-ss approved these changes
Looks good to me!

2024-09-30 07:36 UTC, manojava-gk commented
@ss-nikunj Did you test this scenario in App Management section?

2024-09-30 07:47 UTC, JordanGerada3 approved these changes
Successfully tested locally, LGTM!

2024-09-30 08:44 UTC, ss-nikunj commented
> @ss-nikunj Did you test this scenario in App Management section?

Hi @manojava-gk, Yes I tested it in App Management section. There it is working fine.

2024-10-09 13:58 UTC, evegufy reviewed
could you please update the changelog? (frist rebase to main)

@manojava-gk could you please review?

2024-10-10 06:37 UTC, ss-nikunj commented
@evegufy Rebase & Changelog modified as you mentioned. 

@manojava-gk Can you please review it again?

2024-10-10 06:59 UTC, manojava-gk approved these changes
lgtm

2024-10-11 11:36 UTC, ss-nikunj commented
Hi @evegufy,

@manojava-gk approved this PR. can you please merge it?
Thank you!

2024-10-16 07:48 UTC, oyo approved these changes

2024-10-16 07:49 UTC, oyo commented
@ss-nikunj approved but there are merge conflicts. Can you resolve those please?

2024-10-16 09:10 UTC, oyo requested changes
please resolve merge conflicts

2024-10-17 05:19 UTC, ss-nikunj commented
@oyo Merged conflict resolved! Can you please verify and merge it?

Thank you! 🙂

2024-10-23 09:49 UTC, evegufy commented on CHANGELOG.md
> +
Hi @ss-nikunj we have an continuous issue in the changelog file, the entry is at the wrong place and it's not even shown as conflict. I suggest you add the information which should be added to the changelog in the PR description and I add it then at the next release to the changelog file, sorry for the inconvenience.

2024-10-24 04:45 UTC, ss-nikunj commented
Hi @evegufy, As you mentioned, I have removed the changelog entry and added it to the description.

2024-10-24 06:27 UTC, evegufy approved these changes

2024-10-24 06:55 UTC, oyo approved these changes

2024-10-24 06:56 UTC, merged