fix(UI): service marketplace and detail images
eclipse-tractusx/portal-frontend pull request #1197
Opened 2024-10-04 15:31 UTC by Usmanfee

## Description
Service marketplace and service marketplace detail page has hardcoded images are being displayed. The original image should be displayed incase of its existence otherwise default images would be displayed.

## Solution
There was one parameter of `leadPictureId` was missing in response of api which actually contains the image info so with leadPictureId and now by having `leadPictureId` we are displaying actual images.

## Issue
https://github.com/eclipse-tractusx/portal-frontend/issues/1195

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

2024-10-09 12:57 UTC, shubhamv-ss commented on src/components/pages/ServiceMarketplace/RecommendedServices.tsx
> +                }
This code is used in the below file. Consider converting it into a reusable function for efficiency.

2024-10-09 12:57 UTC, shubhamv-ss commented on src/components/pages/ServiceMarketplace/ServicesElements.tsx
> +                      imagePath={
Try to put this in constant `/images/content/ServiceMarketplace.png`

2024-10-10 08:21 UTC, shubhamv-ss approved these changes
lgtm

2024-10-14 07:42 UTC, typecastcloud commented on CHANGELOG.md
> +  - replaced hardcoded images in service marketplace and detail [#1195](https://github.com/eclipse-tractusx/portal-frontend/issues/1195)
This version was already released. Please move changelog entry to "unreleased".

2024-10-16 14:05 UTC, oyo requested changes
Too much custom image loading logic that already has been implemented. See comments about how to use that. Also please update DEPENDENCIES.

2024-11-04 18:36 UTC, evegufy requested changes
Check for build is failing.

Please also remove the changes to changelog and add a note in the PR description.

2024-11-05 09:43 UTC, Usmanfee commented
@evegufy  I have reverted the change of changelog file. Regarding build failure, failure is expected since I introduced new changes in shared component which is not yet merged and released so that is why it is failing with linting.

https://github.com/eclipse-tractusx/portal-shared-components/issues/356
this above PR first need to be merged and released in order to fix build failure for this PR.

If you have any other suggestion or work around to address this blocker then please let me know! Thanks

2024-11-07 10:00 UTC, evegufy commented
> @evegufy I have reverted the change of changelog file. Regarding build failure, failure is expected since I introduced new changes in shared component which is not yet merged and released so that is why it is failing with linting.
> 
> [eclipse-tractusx/portal-shared-components#356](https://github.com/eclipse-tractusx/portal-shared-components/issues/356) this above PR first need to be merged and released in order to fix build failure for this PR.
> 
> If you have any other suggestion or work around to address this blocker then please let me know! Thanks

Hi @Usmanfee ok understood, @oyo is working on the issue why the integration takes to long, just fyi https://github.com/eclipse-tractusx/portal-shared-components/issues/361

2024-11-26 09:54 UTC, manojava-gk commented
Resolve conflicts and fix pr checks issue

2024-12-12 06:49 UTC, lavanya-bmw commented
Please fix PR checks issue

2024-12-13 14:28 UTC, Usmanfee commented
@evegufy  @manojava-gk  can you please a have review now ? I have resolved conflicts and failed pipeline issue. Thanks

2024-12-16 06:10 UTC, lavanya-bmw approved these changes
lgtm

2025-02-07 10:22 UTC, lavanya-bmw requested changes
Please resolve conflicts

2025-02-07 10:23 UTC, ntruchsess requested changes
as there are new conflicts we cannot proceed. please resolve those new conflicts

2025-02-07 10:24 UTC, manojava-gk reviewed
changes looks fine. but resolve conflicts

2025-02-10 10:01 UTC, Usmanfee commented
@lavanya-bmw  @manojava-gk  can you please check now ? I have resolved the merge conflicts. Thanks

2025-02-12 11:33 UTC, manojava-gk approved these changes
lftm

2025-02-18 05:38 UTC, lavanya-bmw approved these changes

2025-02-27 08:32 UTC, typecastcloud commented on yarn.lock
> +  integrity sha512-rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==
Please do not remove end of file new line.

2025-04-01 08:54 UTC, saadanzari commented
@saadanzari  to add review

2025-05-07 12:15 UTC, saadanzari commented
@Usmanfee pls fix the conflicts and then I can add my review

2025-05-09 11:55 UTC, Usmanfee commented
> @Usmanfee pls fix the conflicts and then I can add my review

@saadanzari  please review. Thanks

2025-05-13 07:22 UTC, JordanGerada3 approved these changes
LGTM!

2025-05-20 10:21 UTC, evegufy commented
> @Usmanfee you can merge this after the requested changes are approved by one of the reviewers

@saadanzari just to clarify, only committers can merge

2025-05-20 10:22 UTC, evegufy approved these changes

2025-05-20 10:35 UTC, ntruchsess approved these changes

2025-05-20 10:39 UTC, merged