feat(usecase): add Business Logic to upload document
eclipse-tractusx/portal-frontend pull request #124
Opened 2023-07-12 09:16 UTC by nidhigarg-bmw

## Description

Connected usecase upload document functionality with business logic

## Why

User can upload document for particular usecase if not exist.

## Issue

N/A

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-07-12 11:58 UTC, manojava-gk reviewed
Small finding

2023-07-12 11:58 UTC, manojava-gk commented on src/components/overlays/EditUsecase/index.tsx
> +          ).replace('{usecaseName}', credentialType),
There is a concept called interpolation. no need to use replace. check checklistOverlay section.
https://www.i18next.com/translation-function/interpolation

2023-07-12 14:15 UTC, oyo requested changes
agree to Mano's remark - there is a better way to replace values in i18n.

2023-07-13 09:16 UTC, manojava-gk approved these changes
lftm

2023-07-13 10:12 UTC, evegufy approved these changes

2023-07-13 10:14 UTC, merged