fix(connector management): resolve cache issue in details overlay
eclipse-tractusx/portal-frontend pull request #1251
Opened 2024-10-17 09:09 UTC by manojava-gk

## Description

do not show regular overlay when error detail is shown. refetch connector details to fix cache issue in the details overlay

## Why

wrong connect info shown behind error overlay

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-10-17 09:10 UTC, manojava-gk commented
@gopalreddy-bmw kindly share ticket info for this issue. I did not find it in the board

2024-11-07 10:42 UTC, evegufy commented
@lavanya-bmw @kunalgaurav-bmw Please review

2024-11-07 10:46 UTC, evegufy requested changes

2024-11-07 10:46 UTC, evegufy commented on CHANGELOG.md
> +  - do not show regular overlay when error detail is shown. refetch connector details to fix cache issue in the details overlay [#1251](https://github.com/eclipse-tractusx/portal-frontend/pull/1251)
Update of changelog in wrong location by now. Please provide update in PR description to avoid conflicts

2024-11-07 16:59 UTC, oyo approved these changes

2024-11-07 17:19 UTC, evegufy approved these changes

2024-11-07 17:20 UTC, merged