feat(onboarding service provider): remove deprecated page
eclipse-tractusx/portal-frontend pull request #1261
Opened 2024-10-21 11:50 UTC by lavanya-bmw

## Description

Removed deprecated page onboardingServiceProvider and every related link

## Why

Since the following page, onboardingServiceProvider was created as a first draft in the past but is not needed anymore

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/1236

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-10-21 13:58 UTC, evegufy requested changes

2024-10-21 13:58 UTC, evegufy commented on CHANGELOG.md
please fix changelog

2024-10-22 04:53 UTC, lavanya-bmw commented on CHANGELOG.md
> please fix changelog

Fixed/updated changelog

2024-10-22 15:24 UTC, oyo approved these changes

2024-10-23 06:30 UTC, evegufy approved these changes

2024-10-23 06:31 UTC, merged