fix(user management): Prevent admins from proceeding further without user
eclipse-tractusx/portal-frontend pull request #1270
Opened 2024-10-23 12:46 UTC by ss-nikunj

## Description
- Once the user/admin has completed the role assignment process, the system allows an admin to proceed to the role assignment section without selecting a user when revisiting the assignment screen. If no new user is chosen, the system defaults to previously selected users.
- The system should display an error message indicating a user must be selected for the role assignment if no new user is chosen.
- Or Admin can not process further if a user is not selected.

## Issue
- https://github.com/eclipse-tractusx/portal-frontend/issues/1267

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

- [x] I have checked that new and existing tests pass locally with my changes

## CHANGELOG
- Fixed: Prevented admins from proceeding with role assignment without selecting a user. [#1267](https://github.com/eclipse-tractusx/portal-frontend/issues/1267)

2024-10-23 12:48 UTC, ss-nikunj commented
Hi @evegufy, As you mentioned in one of my PR. I have added a changelog entry in the description itself.

2024-11-07 10:50 UTC, evegufy requested changes
Please rebase to the current state of the release branch for the latest state of the dependencies file

2024-11-08 11:17 UTC, manojava-gk approved these changes

2024-11-08 11:18 UTC, manojava-gk commented
Changes looks good. Please fix dependency issue

2024-11-08 11:37 UTC, ss-nikunj commented
Hi @evegufy and @manojava-gk, As you mentioned, I have rebased my branch. Can you please review my pr and approve it? 

Thank You!!!

2024-11-08 11:50 UTC, evegufy requested changes
could you please remove this commit https://github.com/eclipse-tractusx/portal-frontend/pull/1270/commits/75a997fb9960395f8370b3522f238ffefed36626, which isn't yours, from your branch (for instance by doing a git rebase release/v2.3.0-RC3 -i and dropping the commit)?

2024-11-13 05:09 UTC, ss-nikunj commented
Hi @evegufy, I have removed the specific commits you mentioned here. Can you please verify it?

Thank you!

2024-11-13 14:06 UTC, evegufy approved these changes

2024-11-13 14:07 UTC, merged