fix: user role description translations in en/de
eclipse-tractusx/portal-frontend pull request #1287
Opened 2024-10-31 15:40 UTC by Usmanfee

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-11-04 04:46 UTC, ss-nikunj reviewed
lgtm

2024-11-07 11:01 UTC, evegufy commented
@kunalgaurav-bmw @lavanya-bmw @manojava-gk please review

2024-11-13 14:56 UTC, oyo requested changes
The original implementation ignored i18n. We should refactor the code so the descriptions are not hard coded in the template csv but instead are taken from the i18n files. This way all i18n translations are in one place and not scattered over the repo.

2024-11-13 14:56 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
> +            CSVCells[0] === 'roles;description_en;description_de'
The implemented solution wouldn't work with more than two languages in case we provide descriptions for additional languages in the future.

2024-11-13 14:56 UTC, oyo commented on public/template_app_role_upload.csv
> +Manager;This is only a test text in EN;Das is in Deutsch
the translations should not appear in this template. Instead we should have them together with the other translations in src/assets/locales.

2024-11-15 09:14 UTC, Usmanfee commented
Absolutely! However, as per my understanding, this is not a translation for some static labels or text. Instead, it pertains to user-driven role description translations, which are always handled through CSV uploads during the app creation phase. Based on the requirement, I made an addition to support the DE language, as per the reported bug.

I also discussed this with @ybidois . The CSV upload process needs to be reconsidered to allow users the flexibility to edit role descriptions. Additionally, we need to evaluate how the UI will look if we expand to more than two languages. For the scope of this ticket, the bug needs to be resolved, but a discussion with UX is required before making any UI changes for role descriptions.

@MaHa-2212 / @ybidois

2025-01-08 11:57 UTC, oyo approved these changes

2025-01-08 11:57 UTC, merged