feat(app & service release process): resume last edited page during registration
eclipse-tractusx/portal-frontend pull request #1376
Opened 2024-11-27 05:47 UTC by kunalgaurav-bmw

## Description

Resume to the last edited page during App/Service registration process.

## Why

Currently if I stop the registration process and then get back to the app/service I need to click through all the steps I fulfilled already, It should be automatically resume to the last page where user stop. 

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/1335

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/admin/Dev%20Process/How%20to%20contribute.md#commits-branches-and-pull-requests-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-12-04 08:29 UTC, evegufy reviewed
@kunalgaurav-bmw please see https://github.com/eclipse-tractusx/portal-frontend/issues/1335#issuecomment-2516533950
@manojava-gk @lavanya-bmw please review

2024-12-04 10:15 UTC, manojava-gk commented
@kunalgaurav-bmw its not registration process -> it is release process. Pls change the text in both title and description

2024-12-04 11:25 UTC, manojava-gk commented
@kunalgaurav-bmw could you pls confirm whether only mandatory fields are being checked to increment or decrement the step?

2024-12-13 09:34 UTC, kunalgaurav-bmw commented
> @kunalgaurav-bmw could you pls confirm whether only mandatory fields are being checked to increment or decrement the step?

Hi @manojava-gk  I have done this changes in useEffect in the following way for the all steps and all the mandatory fields I have added in if condition

useEffect(() => {
    if (hasDispatched.current) return
    if (
      fetchAppStatus?.title &&
      fetchAppStatus.provider &&
      fetchAppStatus.descriptions[0]?.shortDescription &&
      fetchAppStatus.descriptions[1]?.shortDescription &&
      fetchAppStatus.useCase?.length &&
      fetchAppStatus.supportedLanguageCodes?.length &&
      fetchAppStatus.documents?.APP_LEADIMAGE?.length &&
      appRedirectStatus
    ) {
      dispatch(increment())
      hasDispatched.current = true
    }
  }, [fetchAppStatus, hasDispatched])

2024-12-20 06:10 UTC, manojava-gk commented
@kunalgaurav-bmw Is it possible to determine the step based on response in the first step itself?

Create a helper file and move all the step specific conditions to the respective places,
```
function determineStep() {
if(firstStep)
 -> increment(1)
if(secondStep)
 -> increment(2)
 }
 
 function firstStep() {}
 function secondStep() {}
 
 like this ...
 ```

component will have only one condition in first step to determine the actual step. All the step based condition will be hosted in the main method as shown above

2025-01-08 12:17 UTC, oyo requested changes
I'm unable to follow what's happening here - guess we should discuss this in a call.

2025-01-08 12:17 UTC, oyo commented on src/components/pages/AppOverview/index.tsx
> +  }, [])
I haven't seen this pattern in our code before. This returns a cleanup function as described in https://react.dev/reference/react/useEffect#parameters - if the dependency array is empty what difference does it make to not simply call the function but return an internal function?

```
  useEffect(() => {
      dispatch(setAppRedirectStatus(true))
  }, [])
```

2025-01-08 12:17 UTC, oyo commented on src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx
> +
another cleanup function - see my other comment. can you explain the need for that?

2025-01-08 12:17 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +  }, [fetchAppStatus, hasDispatched])
This seems quite complicated and hard to follow. What issue are you trying to solve here?

2025-01-08 12:17 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +
another complicated block

2025-01-28 07:40 UTC, kunalgaurav-bmw commented on src/components/pages/AppOverview/index.tsx
> +  }, [])
Explained

2025-01-28 07:40 UTC, kunalgaurav-bmw commented on src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx
> +
Explained

2025-01-28 07:43 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +
Explained all the mandatory fields I have added in if condition.

2025-01-28 07:43 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +  }, [fetchAppStatus, hasDispatched])
Explained all the mandatory fields I have added in if condition.

2025-02-03 02:56 UTC, manojava-gk approved these changes

2025-02-04 05:32 UTC, lavanya-bmw approved these changes
lgtm

2025-02-04 07:41 UTC, evegufy commented on src/components/pages/AppOverview/index.tsx
> +  }, [])
show how, refer to commit or code section

2025-02-04 07:41 UTC, evegufy commented on src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +  }, [fetchAppStatus, hasDispatched])
show how, refer to commit or code section

2025-02-04 07:41 UTC, evegufy commented on src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +
show how, refer to commit or code section

2025-02-04 07:52 UTC, kunalgaurav-bmw commented on src/components/pages/AppOverview/index.tsx
> +  }, [])
I have created two helper class AppStepHelper and offerStepHelper to manage the steps and here resetting the status on landing AppOverview page please refer to commit [8473552](https://github.com/eclipse-tractusx/portal-frontend/pull/1376/commits/847355214828237573e02757cc7adf45c0e25313)

2025-02-04 07:53 UTC, kunalgaurav-bmw commented on src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx
> +
I have created helper class  offerStepHelper to manage the steps and here reseting the status on landing ServiceListOverview page please refer to commit [8473552](https://github.com/eclipse-tractusx/portal-frontend/pull/1376/commits/847355214828237573e02757cc7adf45c0e25313)

2025-02-04 07:56 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +  }, [fetchAppStatus, hasDispatched])
I handled this in helper class AppStepHelper to manage the steps using required fields please refer to commit  [8473552](https://github.com/eclipse-tractusx/portal-frontend/pull/1376/commits/847355214828237573e02757cc7adf45c0e25313)

2025-02-04 07:57 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +
I handled this in helper class AppStepHelper to manage the steps using required fields please refer to commit  [8473552](https://github.com/eclipse-tractusx/portal-frontend/pull/1376/commits/847355214828237573e02757cc7adf45c0e25313)

2025-02-04 08:07 UTC, evegufy requested changes

2025-02-04 08:07 UTC, evegufy commented on src/components/shared/basic/ReleaseProcess/AppStepHelper/index.tsx
add file header

2025-02-04 08:08 UTC, evegufy requested changes

2025-02-04 08:08 UTC, evegufy commented on src/components/shared/basic/ReleaseProcess/OfferStepHelper/index.tsx
> +import { ConsentStatusEnum } from 'features/serviceManagement/apiSlice'
add file header

2025-02-04 11:00 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/AppStepHelper/index.tsx
file header added

2025-02-04 11:00 UTC, kunalgaurav-bmw commented on src/components/shared/basic/ReleaseProcess/OfferStepHelper/index.tsx
> +import { ConsentStatusEnum } from 'features/serviceManagement/apiSlice'
file header added

2025-02-04 16:43 UTC, evegufy approved these changes

2025-02-04 16:45 UTC, merged