SSI Credential Admin Board
eclipse-tractusx/portal-frontend pull request #141
Opened 2023-07-17 10:08 UTC by nidhigarg-bmw

## Description

Created new page and connected with business logic

## Why

This page is created to see all credential request and whether admin wants to approve/decline

## Issue

CPLP-2924

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-07-18 05:22 UTC, oyo requested changes

2023-07-18 05:22 UTC, oyo commented on src/components/pages/AdminCredential/AdminCredentialElements.tsx
> +      renderCell: ({ row }: { row: any }) => <>{row.useCase ?? 'N/A'}</>,
isn't row of type CredentialData here?

2023-07-18 05:22 UTC, oyo commented on src/assets/locales/de/main.json
> +    },
translate these lines to German to reduce the duplication. If that is planned to be done at a later time, maybe put `de: ` in front of every value

2023-07-19 11:55 UTC, evegufy commented
@nidhigarg-bmw @oyo I created https://github.com/eclipse-tractusx/portal-frontend/pull/147 to address sonarcloud duplications
cc: @jjeroch

2023-07-20 06:42 UTC, oyo requested changes
Locales are now excluded from Sonar checks. Push one dummy commit to re-trigger.

Also the PR title doesn't match conventional commit standards. Please check PR naming scheme here: https://github.com/eclipse-tractusx/portal-frontend/pulls?q=is%3Apr
In doubt read more here: https://www.conventionalcommits.org/en/v1.0.0/

2023-07-20 06:42 UTC, oyo commented
one file causing a merge conflict

2023-07-20 07:14 UTC, oyo approved these changes

2023-07-20 07:14 UTC, merged