fix(app page): fixed phone validation
eclipse-tractusx/portal-frontend pull request #183
Opened 2023-08-02 06:40 UTC by lavanya-bmw

## Description

Fixed validation error for phone number field

## Why

To fix validation error

## Issue

Ref: TEST-1166

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-08-02 13:19 UTC, manojava-gk commented
Kindly fix the Sonar Bug

2023-08-03 09:57 UTC, oyo requested changes

2023-08-03 09:57 UTC, oyo commented on src/types/Patterns.ts
> +    phone: /^\+(\d{2})?(\s?)+(\(\d{3}\))?\s?\d{10,13}$/,
Three things here:
1. fix the sonar bug - something like changing `(\s?)+` to `\s+` should work
2. add a convenience method `isPhone` for that. Scroll down to line 90+ and add it similar to the existing methods.
3. regular expressions are among the things where unit tests make the most sense. Especially if they are not self explanatory like this one here. Someone before added this regex and forgot to add tests. Go to `Patterns.test.ts` and add values for valid and invalid phone numbers similar to the existing tests. Then run `yarn test Patterns` to check if to regular expression works correctly.

2023-08-22 11:27 UTC, jjeroch commented
decision: pr against dev instead of 1.6.0

2023-08-25 06:57 UTC, oyo approved these changes

2023-08-25 06:59 UTC, oyo requested changes
please resolve merge conflicts

2023-09-11 11:36 UTC, oyo approved these changes

2023-09-11 11:37 UTC, merged