feat(app overview): implemented add roles
eclipse-tractusx/portal-frontend pull request #225
Opened 2023-08-22 06:42 UTC by lavanya-bmw

## Description

Add roles functionality is added to app overview active apps

## Why

To enhance active apps functionality

## Issue

Ref: CPLP-1563, CPLP-1564

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-08-22 07:45 UTC, oyo requested changes
one tiny change

2023-08-22 07:45 UTC, oyo commented on src/components/pages/AppOverview/AddRolesOverlay.tsx
> +                  'https://portal.dev.demo.catena-x.net/documentation/?path=docs%2F04.+App%28s%29%2FRelease-Process%2FApp+Release+Workflow.md',
please make this a relative link by removing this part:

`https://portal.dev.demo.catena-x.net`

2023-08-22 08:27 UTC, oyo submitted a review, later dismissed

2023-08-22 09:05 UTC, jjeroch requested changes
Wrong branch

2023-08-25 07:01 UTC, oyo approved these changes

2023-08-25 07:01 UTC, merged