feat(user bulk upload): bulk upload ownidp
eclipse-tractusx/portal-frontend pull request #230
Opened 2023-08-23 07:41 UTC by nidhigarg-bmw

## Description

User bulk upload ownidp

## Why

Add functionality for ownidp scenario

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-08-23 11:57 UTC, manojava-gk approved these changes
lftm

2023-08-25 06:49 UTC, oyo requested changes

2023-08-25 06:49 UTC, oyo commented on src/components/overlays/AddMultipleUser/index.tsx
> +              loadIndicator="Loading ..."
Translation?

2023-08-25 06:49 UTC, oyo commented on src/components/overlays/AddMultipleUser/index.tsx
> +            onCloseWithIcon: () => dispatch(show(OVERLAYS.NONE, '')),
use `dispatch(closeOverlay())`

2023-08-28 04:19 UTC, nidhigarg-bmw commented
@oyo  Made the changes

2023-08-31 06:50 UTC, oyo approved these changes

2023-08-31 06:50 UTC, merged