feat(technical user details): reset credential
eclipse-tractusx/portal-frontend pull request #245
Opened 2023-09-01 06:32 UTC by manojava-gk

## Description

add reset credential button and respective api integration

## Why

new request

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-09-01 07:44 UTC, lavanya-bmw approved these changes
lgtm

2023-09-05 07:41 UTC, manojava-gk commented
@evegufy  can you merge this PR? Lavanya has already approved it

2023-09-06 08:23 UTC, evegufy commented on src/assets/locales/de/main.json
> +        "resetCredentialSuccess": "Reset credential is successful",
Could you please change the message here to "Credential reset was successful"?

2023-09-06 08:25 UTC, evegufy commented on src/assets/locales/en/main.json
> +        "resetCredentialSuccess": "Reset credential is successful",
Could you please change the message here to "Credential reset was successful"?

2023-09-06 08:30 UTC, evegufy commented on src/assets/locales/de/main.json
> +        "resetCredentialSuccess": "Reset credential is successful",
Could you please change the message here to "Credential reset was successful"?

2023-09-06 08:36 UTC, evegufy requested changes
Please also adjust the 'Why' in the PR description: 'new request' isn't very helpful description, at this point simply 'enable new functionality' I'd consider a more helpful information.

2023-09-06 08:36 UTC, evegufy commented on CHANGELOG.md
> +  - Reset credential
Could you please change to "Enable credential reset"?
I think that leaves less room for interpretation.

2023-09-08 06:56 UTC, evegufy requested changes
My comments regarding success message weren't implemented

2023-09-08 07:25 UTC, evegufy approved these changes

2023-09-08 07:26 UTC, merged