bugfix(app subscription): activation action
eclipse-tractusx/portal-frontend pull request #260
Opened 2023-09-11 09:22 UTC by manojava-gk

## Description

 activate button showing service activation screen instead of app activation

## Why

wrong overlay being shown on activation

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-09-11 09:35 UTC, manojava-gk commented
**DO NOT MERGE UNTILL NIDHI APPROVES**

2023-09-11 09:37 UTC, evegufy requested changes

2023-09-11 09:37 UTC, evegufy commented on CHANGELOG.md
> +- Bugfix - App Subscription
Please but this fix under the already existing section for app subscription.

2023-09-12 05:38 UTC, nidhigarg-bmw approved these changes
lftm.

2023-09-12 06:08 UTC, evegufy commented
@manojava-gk please update the dependencies file

2023-09-12 06:11 UTC, manojava-gk commented
> @manojava-gk please update the dependencies file

there is no new dependency file in the summary. But this issue is happening for every PR now.

2023-09-12 09:13 UTC, evegufy commented
IP issue created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10499

2023-09-12 09:40 UTC, evegufy commented
@manojava-gk you can rcommit the dependencies file now

2023-09-12 11:14 UTC, evegufy approved these changes

2023-09-12 11:15 UTC, merged