fix(service release process): Skip technical integration
eclipse-tractusx/portal-frontend pull request #277
Opened 2023-09-20 04:12 UTC by lavanya-bmw

## Description

Skip technical integration for consultancy service

## Why

The "Consultancy Service" was renamed 

## Issue

Ref: CPLP-3248

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-09-22 06:23 UTC, manojava-gk approved these changes
lftm

2023-09-25 11:57 UTC, oyo requested changes
there's a little thing we can improve

2023-09-25 11:57 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
> +      : skipTechnicalIntegrationStep(true)
we can write this better. 
Instead of

`condition ? doSomething(false) : do Something(true)`

write

`doSomething(!condition)`

2023-09-27 12:07 UTC, oyo approved these changes

2023-09-27 12:07 UTC, merged