feat(idp): user migration error handling
eclipse-tractusx/portal-frontend pull request #340
Opened 2023-11-06 07:03 UTC by nidhigarg-bmw

## Description

Idp User Migration Error Handling Logic

## Why

UI Enhancement

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-11-06 08:57 UTC, manojava-gk approved these changes
lftm

2023-11-08 19:35 UTC, jjeroch commented on CHANGELOG.md
> +  - Error Handling Logic
Lets be a bit more specific - something like that:

- extended error handling of the api response message implemented
- included csv file upload validation of csv header row content

2023-11-10 09:36 UTC, oyo requested changes

2023-11-10 09:36 UTC, oyo commented on src/components/overlays/AddusersIDP/index.tsx
> +        ]
see https://github.com/eclipse-tractusx/portal-frontend/pull/339#discussion_r1389140597

2023-11-13 04:23 UTC, oyo approved these changes

2023-11-13 04:24 UTC, merged