bugfix(notification): change navigation link to service marketplace
eclipse-tractusx/portal-frontend pull request #341
Opened 2023-11-06 09:10 UTC by manojava-gk

## Description

change navigation from  Company Role Service Provider  to service marketplace

## Why

Link should lead to Service Provider Marketplace as described in notification. https://portal.int.demo.catena-x.net/servicemarketplace

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-11-06 15:24 UTC, jjeroch requested changes

2023-11-10 09:45 UTC, oyo requested changes
check redundant i18n definitions

2023-11-10 09:45 UTC, oyo commented on src/assets/locales/de/notification.json
> +    "servicemarketplace": "Get there"
@jjeroch, @manojava-gk - definitely agree that we should pay attention to reuse. If we notice some texts are occurring repeatedly in our application (or have the potential to be reused in the future) we don't need to define it every time again and have created a section `global.actions.something` (or `global.field.something`) for that here:
https://github.com/eclipse-tractusx/portal-frontend/blob/main/src/assets/locales/en/main.json#L1688-L1714

2023-11-10 10:51 UTC, manojava-gk commented on src/assets/locales/de/notification.json
> +    "servicemarketplace": "Get there"
@oyo both navigation and button name are handled dynamically in the NotificationConfig component. Kindly look at the code once and let me know your thoughts.

2023-11-13 04:32 UTC, oyo approved these changes

2023-11-13 04:32 UTC, oyo commented on src/assets/locales/de/notification.json
> +    "servicemarketplace": "Get there"
@manojava-gk understand - the key is also the target page. Still not really beautiful but the other option - handing over another parameter like `label="default"` brings other overhead. So I guess we can go with your solution.

2023-11-13 04:32 UTC, merged