feat(subscription): pattern and api
eclipse-tractusx/portal-frontend pull request #403
Opened 2023-12-15 07:24 UTC by manojava-gk

## Description

update company name patter and respective unit test cases. add companyName query param to the subscription url

## Why

enhance search feature

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-12-15 08:59 UTC, nidhigarg-bmw approved these changes
lgtm

2023-12-26 05:19 UTC, lavanya-bmw requested changes
Please add change log

2024-01-08 03:27 UTC, oyo requested changes
one tiny change - otherwise okay

2024-01-08 03:27 UTC, oyo commented on src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx
> +    const validateExpr = Patterns.COMPANY_NAME.test(expr)
please use from Patterns.ts:

`isCompanyName(expr)`

2024-01-08 09:15 UTC, oyo approved these changes

2024-01-08 09:15 UTC, merged