fix(technical integration): role upload findings
eclipse-tractusx/portal-frontend pull request #404
Opened 2023-12-15 07:30 UTC by lavanya-bmw

## Description

Fixed help link, funky character display and the success message display in user role upload

## Why

To display valid/proper data

## Issue

Ref: CPLP-3473

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-12-15 08:02 UTC, nidhigarg-bmw approved these changes
lgtm

2023-12-27 06:21 UTC, manojava-gk approved these changes
lftm

2024-01-08 03:34 UTC, oyo requested changes
question about uncommon character encoding.

2024-01-08 03:34 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
> +        reader.readAsText(file, 'ISO-8859-4')
ISO-8859-4 is a specific encoding for north european countries (https://en.wikipedia.org/wiki/ISO/IEC_8859-4) - our files should generally be in unicode, specifically utf-8

Does `reader.readAsText(file, 'utf-8')` not work?

If it doesn't work then the file is probably in an unsupported encoding and the user should make sure to only upload files that are in supported formats.

2024-01-25 08:51 UTC, oyo requested changes
one tiny remark

2024-01-25 08:51 UTC, oyo commented on src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
> +      value: 'utf-8',
Hey, doesn't it understand uppercase 'UTF-8'? - I think it should also work and looks nicer if all are upper case

2024-01-26 05:16 UTC, oyo approved these changes

2024-01-26 05:17 UTC, merged

2024-01-29 23:56 UTC, jjeroch commented
rollback needed - issue: 

- wrong branch
- wrong changeLog update

@oyo  as we spoke - please make sure that 2 level pr check is executed - ping me if you need a quick check instead of merging with a single review