feat(decline-registration): decline registration confirmation logic
eclipse-tractusx/portal-frontend pull request #405
Opened 2023-12-21 11:44 UTC by nidhigarg-bmw

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-01-23 09:06 UTC, jjeroch commented
recheck the branch please - as per the ticket this should be release branch related

2024-01-25 08:53 UTC, oyo requested changes
update header dates

2024-01-25 08:53 UTC, oyo commented on src/components/pages/DeleteCompany/DeleteCompany.scss
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
2024

2024-01-25 08:53 UTC, oyo commented on src/components/pages/DeleteCompany/index.tsx
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
2024

2024-01-25 08:53 UTC, oyo commented on src/features/deleteCompany/deleteCompanyApiSlice.ts
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
2024 and remove BMW line

2024-01-25 10:13 UTC, nidhigarg-bmw commented on src/features/deleteCompany/deleteCompanyApiSlice.ts
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
@oyo Updated all the headers

2024-01-25 13:09 UTC, merged