update(idp): add error for snackbar
eclipse-tractusx/portal-frontend pull request #408
Opened 2024-01-04 08:04 UTC by lavanya-bmw

## Description

Added snackbar for idp error

## Why

To display error in snackbar

## Issue

Ref: CPLP-3591

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-01-08 23:29 UTC, jjeroch commented
@lavanya-bmw i suggest to improve the description of the pr slightly - reason: it is easier for others to understand the change.

Suggestion:

Description
"Added api error handling component (snackbar) for the FE flow for GET /company/identityproviders which is called inside the user account creation flow"

Why
"Until now the error scenario was not handled which resulted into a bad user experience due to failing api on the backend while FE screen was not giving any response to the user"

2024-01-08 23:31 UTC, jjeroch commented
@lavanya-bmw can we solve the 3 issues created in the sonar review?

2024-01-08 23:31 UTC, jjeroch requested changes
comments added

2024-01-09 08:03 UTC, oyo approved these changes

2024-01-09 08:03 UTC, merged