feat(wallet): company wallet
eclipse-tractusx/portal-frontend pull request #424
Opened 2024-01-19 08:27 UTC by manojava-gk

## Description

Company wallet listing page along with api integration

## Why

new feature

## Issue
NALink to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-01-23 06:12 UTC, manojava-gk commented
FYI - Zero linter issues in newly created folders

2024-01-23 06:21 UTC, manojava-gk commented on src/types/Constants.ts
> +  COMPANY_WALLET = 'CX Admin',
@jjeroch Please provide role info

2024-01-24 16:24 UTC, jjeroch requested changes
- Grouping update needed
  - Group 1: "Frameworks" shows all credentials with credential type "Framework.*" 
  - Group 2: "Company Role" shows all credentials with credential type "CompanyRole.*"
  - Group 3: "Others" shows all other credentials which are responded
- where the BPNL is currently displayed, there the Credential Type should be shown (big and bold)
- Where the current credential type is displayed, there the BPNL should show up (small and not bold)
- Please mention "Expiry:" in front of the expiry date

2024-01-25 07:04 UTC, manojava-gk commented
> * Grouping update needed
>   
>   * Group 1: "Frameworks" shows all credentials with credential type "Framework.*"
>   * Group 2: "Company Role" shows all credentials with credential type "CompanyRole.*"
>   * Group 3: "Others" shows all other credentials which are responded
> * where the BPNL is currently displayed, there the Credential Type should be shown (big and bold)
> * Where the current credential type is displayed, there the BPNL should show up (small and not bold)
> * Please mention "Expiry:" in front of the expiry date

Addressed the comments. but waiting for appropriate data to test @jjeroch

2024-01-25 08:57 UTC, oyo approved these changes

2024-01-25 13:53 UTC, jjeroch requested changes

2024-01-25 13:53 UTC, jjeroch commented on src/assets/locales/de/main.json
> +      "expiry": "Expiry: "
German Translation? ;)

2024-01-25 14:35 UTC, manojava-gk commented on src/assets/locales/de/main.json
> +      "expiry": "Expiry: "
Check now

2024-01-26 05:13 UTC, merged