feat(service subscription activation) : ui updates and api integration
eclipse-tractusx/portal-frontend pull request #45
Opened 2023-05-29 07:16 UTC by manojava-gk

## Description

Service subscription activation flow updates
1. Show tech user details if present in both register and activation overlay
2. autosetup api to connect with backend

## Why

1. Service subscription activation api integration was missing
2. Service subscription activation flow was using  app subscription activation flow which is slightly different

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-05-29 21:28 UTC, oyo approved these changes

2023-05-30 06:09 UTC, lavanya-bmw approved these changes

2023-05-30 16:29 UTC, oyo requested changes
please resolve changelog conflict

2023-05-31 07:13 UTC, oyo approved these changes

2023-05-31 07:14 UTC, merged