fix(company role): show company role specific standard library info
eclipse-tractusx/portal-frontend pull request #480
Opened 2024-02-06 11:16 UTC by manojava-gk

## Description

Show company role specific standard library info in the table instead of all.

## Why

do not show all std library info in the company role page

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-08 07:10 UTC, manojava-gk commented
@oyo do you have any comments?

2024-02-08 07:47 UTC, oyo requested changes
some changes - especially the logic seems to be incorrect

2024-02-08 07:47 UTC, oyo commented on src/components/pages/CompanyRoles/index.tsx
>        if (url.indexOf('companyrolesappprovider') > 1) {
I guess that should be > -1 ?
but generally use .includes(x) instead of .indexOf(x) > -1

don't use hard coded strings - use enum string types

2024-02-08 07:47 UTC, oyo commented on src/components/pages/CompanyRoles/index.tsx
> +  }
unnecessary return:
```

const getFiltered = (std: StandardLibraryType, cr: number[]) =>
  std.rows.filter(
    (row: { roles: number[] }) => intersect(row.roles, cr).length > 0
  )
```

2024-02-12 13:46 UTC, oyo approved these changes

2024-02-12 13:46 UTC, merged