feat(company certificate):
eclipse-tractusx/portal-frontend pull request #528
Opened 2024-02-20 13:17 UTC by manojava-gk

## Description

connect listing page, upload certificate and details page to back end api

## Why

connect static content with apis

## Issue

#460 #461 #462 

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-20 21:22 UTC, jjeroch approved these changes

2024-02-21 03:50 UTC, oyo requested changes
some remarks

2024-02-21 03:50 UTC, oyo commented on src/features/companyCertification/companyCertificateApiSlice.tsx
> +        url: `/api/administration/documents/${documentId}`,
why use .mutation for GET requests which are supposed to be not state changing?

2024-02-21 03:50 UTC, oyo commented on src/features/companyCertification/companyCertificateApiSlice.tsx
> +  expiryDate: any
expiry date could be a date, string or number - but not any

2024-02-21 03:50 UTC, oyo commented on src/components/pages/CompanyCertificates/index.tsx
> +  }, [data])
this can probably be done without a useEffect

2024-02-21 03:50 UTC, oyo commented on src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
> +        console.log(data)
console.log should not go into production code

2024-02-21 03:50 UTC, oyo commented on src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
> +          expiryDate: date?.toISOString(),
here it looks like
expiryDate: string | undefined
why not use that and define as any?

2024-02-21 03:50 UTC, oyo commented on src/components/overlays/CompanyCertificateDetails/index.tsx
> +  }, [])
we don't need this useEffect if getDocument is implemented as query and not a mutation - which is the right way here

2024-02-21 03:50 UTC, oyo commented on src/components/overlays/CompanyCertificateDetails/index.tsx
> +  const [getDocument] = useFetchDocumentMutation()
Why use mutation instead of query for a GET request?

2024-02-21 03:50 UTC, oyo commented on src/components/overlays/CompanyCertificateDetails/index.tsx
> +  }, [companyData])
can't we simply initialize selected in line 72 instead of this useEffect?

2024-02-21 06:12 UTC, oyo approved these changes

2024-02-21 06:12 UTC, merged