fix(user menu): full height user menu
eclipse-tractusx/portal-frontend pull request #558
Opened 2024-02-29 05:52 UTC by manojava-gk

## Description

display full width menu. move menu footer to the bottom section.
no custom style for sub navigation header

## Why

new change request

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-29 07:07 UTC, lavanya-bmw requested changes
Please add changelog

2024-02-29 07:07 UTC, lavanya-bmw commented on src/components/shared/MobileMenu/index.tsx
> +            <NotificationLink to={'/notifications'} />
Please remove hardcoded link and add this from constants

2024-02-29 07:59 UTC, lavanya-bmw approved these changes
lgtm

2024-02-29 16:34 UTC, manojava-gk commented
@evegufy can you merge this PR?

2024-02-29 17:32 UTC, evegufy commented
@manojava-gk is there no issue for this change?

2024-03-01 04:32 UTC, manojava-gk commented
> @manojava-gk is there no issue for this change?

No. I have tested this in the local

2024-03-04 10:03 UTC, manojava-gk commented
@oyo @nidhigarg-bmw @lavanya-bmw Kindly review once again

2024-03-04 10:16 UTC, nidhigarg-bmw approved these changes
lftm

2024-03-04 10:36 UTC, oyo approved these changes

2024-03-04 10:36 UTC, merged