feat(my account): add admin info to issuer info table
eclipse-tractusx/portal-frontend pull request #63
Opened 2023-06-08 11:33 UTC by nidhigarg-bmw

## Description

User Account & My User Account: Add Admin Info

## Why

Adding Admin Emails to Issuer Table

## Issue

CPLP-2815

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-06-09 04:41 UTC, lavanya-bmw approved these changes
lgtm

2023-06-11 11:13 UTC, oyo requested changes

2023-06-11 11:13 UTC, oyo commented on cx-portal/src/features/admin/userOwn/mapper.ts
> +}
this function is not needed - see below

2023-06-11 11:13 UTC, oyo commented on cx-portal/src/features/admin/userOwn/mapper.ts
> +        value: user.admin?.length ? getAdminEmails(user.admin) : 'N/A',
sure this value should be an array and not a string?
Anyway, better replace
`getAdminEmails(user.admin)`
with
`user.admin?.map((data: AdminData) => data.email)`

2023-06-12 06:31 UTC, nidhigarg-bmw commented on cx-portal/src/features/admin/userOwn/mapper.ts
> +}
@oyo Made the changes as requested

2023-06-12 06:31 UTC, oyo submitted a review, later dismissed

2023-06-12 06:34 UTC, oyo approved these changes

2023-06-12 06:35 UTC, merged