fix(error handling): display error page if backend not available
eclipse-tractusx/portal-frontend pull request #762
Opened 2024-05-06 07:21 UTC by nidhigarg-bmw

## Description

Display Error page if backend not available

## Why

When backend isn't available, the app continuously sends thousands of requests

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/632

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2024-05-06 07:30 UTC, evegufy requested changes
Please wait for approval from @jjeroch

2024-05-07 09:10 UTC, oyo approved these changes

2024-05-08 08:24 UTC, nidhigarg-bmw commented
@evegufy @jjeroch The Error page will look like this
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/5bc0f8ae-d9d9-412c-8482-104d0e085e96)
And this page will only work if backend isnt available. And it wont affect other error handlings and functionalities which are working before.

2024-05-08 08:44 UTC, evegufy approved these changes

2024-05-08 08:45 UTC, merged