feat(app marketplace): add more and collapse
eclipse-tractusx/portal-frontend pull request #805
Opened 2024-05-17 06:33 UTC by lavanya-bmw

## Description

Add more and collapse button to category view

## Why

To improve the 'more' button functionality to category view in app marketplace

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/688

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-05-20 06:48 UTC, manojava-gk reviewed
small comment. Rest looks fine

2024-05-20 06:48 UTC, manojava-gk commented on src/components/pages/AppMarketplace/components/AppListGroup/index.tsx
> +      return (4).toString()
Can use one method to handle this??
```
setItemsShown(() => {
return itemsToShow.length >= items.length ? (4).toString() : items.length.toString()
})
```

2024-05-20 06:48 UTC, manojava-gk commented on src/components/pages/AppMarketplace/components/AppListGroup/index.tsx
> +            ? collapseItemsShown
Same as above

2024-05-20 07:13 UTC, lavanya-bmw commented on src/components/pages/AppMarketplace/components/AppListGroup/index.tsx
> +            ? collapseItemsShown
Done

2024-05-21 07:35 UTC, oyo requested changes

2024-05-21 07:35 UTC, oyo commented on src/assets/locales/de/main.json
> +      "collapse": "Zusammenbruch",
haha - that's an ambiguous translation. In this context I guess the correct german term is "Einklappen"

2024-05-21 07:35 UTC, oyo commented on src/components/pages/AppMarketplace/components/AppListGroup/index.tsx
>    }
First of all why is `itemsToShow` a string in the old code? That doesn't make any sense and should be fixed here to number. Then the entire function can be written more readable as one line (maybe prettier might reformat):
` const handleMoreAndCollapse = () => setItemsShow(itemsToShow.length >= items.length ? 4 : items.length `

2024-05-21 14:11 UTC, oyo submitted a review, later dismissed

2024-05-22 05:20 UTC, evegufy submitted a review, later dismissed

2024-05-22 05:22 UTC, evegufy commented
@jjeroch Could you please confirm that this PR should merged to 24.05 anymore but to 24.08 according to the milestone on https://github.com/eclipse-tractusx/portal-frontend/issues/688?

2024-05-22 06:40 UTC, jjeroch commented
@evegufy  & @lavanya-bmw  we should add this to 24.08. please. This is not mission critical for 24.05.

2024-05-22 06:58 UTC, evegufy commented
Merge to dev once 2.0.0-RC4 was merged dev

2024-05-29 06:21 UTC, evegufy approved these changes

2024-05-29 06:22 UTC, merged