fix(application request): add open overlay on progress button click
eclipse-tractusx/portal-frontend pull request #808
Opened 2024-05-17 12:58 UTC by nidhigarg-bmw

## Description

Add open overlay on progress button click

## Why

To open the overlay on button click for good user experience

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/740

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2024-05-20 04:31 UTC, manojava-gk reviewed
Small findings. Rest looks good

2024-05-20 04:31 UTC, manojava-gk commented on src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +    if (params.field === 'detail' || params.field === 'status') {
Can you use enum here?

2024-05-20 04:31 UTC, manojava-gk commented on src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +      setSelectedActiveTab(params.field === 'detail' ? 0 : 1)
Can you use enum here?

2024-05-20 04:51 UTC, lavanya-bmw requested changes
Please add changelog

2024-05-20 04:56 UTC, nidhigarg-bmw commented
> Please add changelog

No needed

2024-05-20 06:42 UTC, nidhigarg-bmw commented on src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +    if (params.field === 'detail' || params.field === 'status') {
@manojava-gk Made the changes

2024-05-20 16:05 UTC, lavanya-bmw approved these changes
lgtm

2024-05-21 07:40 UTC, oyo approved these changes

2024-05-21 13:11 UTC, merged