fix(semantic hub): display error bar
eclipse-tractusx/portal-frontend pull request #917
Opened 2024-07-11 06:44 UTC by lavanya-bmw

## Description

Show appropriate error information to the user along with reload

## Why

To enhance error handling

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/891

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-07-15 11:23 UTC, lavanya-bmw commented on src/components/pages/SemanticHub/ModelTable.tsx
> +      error && Number(error) >= 400 && Number(error) < 500
Fixed

2024-07-16 06:20 UTC, manojava-gk approved these changes
lgtm

2024-07-16 11:41 UTC, oyo requested changes
see comments about how to get rid of any type

2024-07-16 11:41 UTC, oyo commented on src/features/semanticModels/types.ts
> +  error: any
please define an interface for ErrorResponse containing all the attributes you like to access. Like here we use `error.response.status` 

```
export interface ErrorResponse {
  response: {
    status: number
  }
}

...

  error: ErrorResponse
```

2024-07-16 11:41 UTC, oyo commented on src/features/semanticModels/actions.ts
> +    } catch (error: any) {
import and use the ErrorResponse type from other comment

2024-07-16 11:44 UTC, oyo requested changes

2024-07-16 11:44 UTC, oyo commented on src/features/semanticModels/actions.ts
> +      throw Error(JSON.stringify(error.response.status))
`(error as ErrorResponse).response.status`

2024-07-22 07:00 UTC, oyo approved these changes

2024-07-22 07:00 UTC, merged