fix(role): typo fix for the role to hide admin board page for service manager
eclipse-tractusx/portal-frontend pull request #937
Opened 2024-07-15 15:18 UTC by saadanzari

## Description

**Current Behavior**
Service Management -> Admin Board page is not showing the Services and responding 403 Forbidden error.

**Expected Behavior**
Service Manager should be able to see services list on Admin Board page OR Service Manager should not see Admin Board sub-menu option under Service Management menu if Service Manager doesn't supposed to have related permissions.

**Steps To Reproduce**
- Login to the portal as a Service Manager
- Mouse Hover on Service Management menu and click on Admin Board option

**Findings**
Service Management -> Admin Board page is calling the API: https://portal-backend.entry.cofinity-x.com/api/services/serviceRelease/inReview?size=15&page=0&status=InReview&sorting=DateDesc

and this API has following permissions:
- approve_service_release
- decline_service_release

but Service Manager user account doesn’t have such permissions.

## Why
In frontend these are the following roles:

APPROVE_SERVICE_RELEASE = 'activate_subscription'
DECLINE_SERVICE_RELEASE = 'decline_service_release'

So, the issue seems to be at the frontend side that APPROVE_SERVICE_RELEASE variable as wrong role value (activate_subscription) which needs to be corrected by approve_service_release value so, that this Admin Board page would only be visible to the users who would have same roles as API roles.

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/936

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

2024-07-16 13:11 UTC, evegufy requested changes
Thank for the contributions!

could you please solve the conflict with the changelog file?

Please also update the dependencies file (you can download the artifact here and commit the updated file https://github.com/eclipse-tractusx/portal-frontend/actions/runs/9956456758?pr=937)

In general, it would be great if you could not link to closed systems like your entry "entry" environment, such an example link is much more friendly in the open: https://portal-backend.example.org/api/services/serviceRelease/inReview?size=15&page=0&status=InReview&sorting=DateDesc

2024-07-24 11:58 UTC, oyo approved these changes

2024-07-24 12:09 UTC, evegufy approved these changes

2024-07-24 12:11 UTC, oyo approved these changes

2024-07-24 12:11 UTC, merged