feat(ospm): create new page
eclipse-tractusx/portal-frontend pull request #962
Opened 2024-07-24 06:39 UTC by lavanya-bmw

## Description

Create new page for onboarding service provider management

## Why

NA

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/541

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-07-24 12:20 UTC, oyo requested changes
a few suggestions and one question

2024-07-24 12:20 UTC, oyo commented on src/types/Constants.ts
> +  ONBOARDING_SERVICE_PROVIDER = 'onboardingServiceProvider',
Above in Line 105 we already have 

`ONBOARDING_SERVICEPROVIDER = 'onboarding-serviceprovider',`

Is this a duplicate?

2024-07-24 12:20 UTC, oyo commented on src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
> +            </IconButton>
this block is very similar to the one in L87-L99 - I suggest you create a local component on top of the file and just specify the child and right / left

2024-07-24 12:20 UTC, oyo commented on src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
> +        </Tabs>
again too much duplication - better create a local component with props for the differences

2024-07-25 17:21 UTC, evegufy requested changes
testing for 24.08 ends officially in less than 24h, please don't merge without me confirming but the change will very likely not go into the 2.1.0 release anymore, I'll let you know tomorrow

2024-07-29 10:46 UTC, evegufy commented
confirmed: v2.1.0 is closed,  please change to main

2024-08-04 17:11 UTC, MaximilianHauer commented
@lavanya-bmw  can you please have a look on the notes of Martin.

2024-08-27 17:07 UTC, closed without merging