feat(technical user management): enhance table with status column
eclipse-tractusx/portal-frontend pull request #967
Opened 2024-07-26 06:02 UTC by lavanya-bmw

## Description

Enhance technical user table by adding StatusTag to the status column by fetching the status from the backend 

## Why

To enhance technical user table by adding StatusTag to the status column 

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/944

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-07-26 06:32 UTC, lavanya-bmw commented
This PR to be merged once https://github.com/eclipse-tractusx/portal-shared-components/pull/249 is merged

2024-08-05 05:42 UTC, MaximilianHauer commented
@lavanya-bmw shard-component pr is merged please proceed.

2024-08-05 06:04 UTC, lavanya-bmw commented
> @lavanya-bmw shard-component pr is merged please proceed.

@oyo @kunalgaurav-bmw Can you please review this PR(this is merge ready)

2024-08-08 08:19 UTC, kunalgaurav-bmw approved these changes
Looking fine for me :)

2024-08-08 13:44 UTC, oyo requested changes
please use types instead of strings from the beginning - this makes the code easier to understand

2024-08-08 13:44 UTC, oyo commented on src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
> +
define and use this type in the apiSlice

2024-08-08 13:44 UTC, oyo commented on src/features/admin/serviceApiSlice.ts
> +  status: string
Define the type ServiceAccountStatus here and use it

2024-08-08 13:44 UTC, oyo commented on src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
> +
the type ServiceAccountStatus has a number of values - so best is to create a map

```
const statusColorMap: Record<ServiceAccountStatus, string> = {
  ServiceAccountStatus.ACTIVE: 'confirmed',
  ServiceAccountStatus.INACTIVE: 'declined',
  ServiceAccountStatus.DELETED: 'deleted',
  ServiceAccountStatus.PENDING: 'pending',
  ServiceAccountStatus.PENDING_DELETION: 'pending',
}
```

2024-08-08 13:44 UTC, oyo commented on src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
> +                color={renderStatusColor(row.status)}
here use the map created:

```
color={statusColorMap[row.status]}
```

2024-08-12 12:33 UTC, oyo approved these changes

2024-08-12 12:34 UTC, merged