fix(service detail): add missing header image implementation
eclipse-tractusx/portal-frontend pull request #992
Opened 2024-08-08 11:00 UTC by JordanGerada3

## Description

- Added function to create image object url
- Added image type constants
- Buffer to hex conversion function

## Why

Upon opening any service detail, images set during service onboarding were not being displayed and only a static default image was being rendered for all services. due to missing/not yet present implementation. 

## Issue

#990 

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-08 14:36 UTC, oyo requested changes
We already implemented a very similar image loading mechanism in a generic Image component:
https://github.com/eclipse-tractusx/portal-shared-components/blob/main/src/components/basic/Image/index.tsx

The idea is to pass the URL and a loader function (fetchImageWithToken) - the component will then try to load and render the image or show a standard default image in case something goes wrong. I suggest to somehow make use of or modify the existing components instead of rewriting a lot of similar code.

2024-08-08 14:36 UTC, oyo commented on src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
> +  const [image, setActualImage] = useState<string>('')
by convention destructured useState variables should always be named
`[someValue, setSomeValue] = useState...`

see sonar finding: https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=992&id=eclipse-tractusx_portal-frontend&open=AZExprbVdf87lRO01BrH

2024-08-08 14:36 UTC, oyo commented on src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
> +  }
use ternary operator ` ? : `
```
const getImageUrl = () => 
  fetchServiceStatus
    ? `${getAssetBase()}/api/administration/documents/${fetchServiceStatus.leadPictureId}`
    : `${getAssetBase()}/images/content/ServiceMarketplace.png`
```

2024-08-08 14:36 UTC, oyo commented on src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
> +        console.error('An error occurred while fetching the image:', error)
for images I suggest not to output an error to the console but simply show a fallback image

2024-08-14 08:57 UTC, JordanGerada3 commented
> We already implemented a very similar image loading mechanism in a generic Image component: https://github.com/eclipse-tractusx/portal-shared-components/blob/main/src/components/basic/Image/index.tsx
> 
> The idea is to pass the URL and a loader function (fetchImageWithToken) - the component will then try to load and render the image or show a standard default image in case something goes wrong. I suggest to somehow make use of or modify the existing components instead of rewriting a lot of similar code.

@oyo thank you for your review. I have considered your request and made changes where still relevant, however I have since created a different change. This HorizontalCard component is also used in appDetail, so I have decided to just follow the same implementation already used elsewhere in the marketplace. The HorizontalCard also displays a default dummy image if the url provided is invalid, hence the console.log if an error is caught.

2024-08-30 09:48 UTC, oyo requested changes
looks good but license file header for new files is missing

2024-08-30 13:32 UTC, JordanGerada3 reviewed
I have removed the Buff2Hex function.

2024-08-30 13:32 UTC, JordanGerada3 commented on src/utils/buff2hex.ts
> +export const Buff2Hex = (buffer: ArrayBuffer): string =>
@oyo thanks for spotting that! Actually I have removed this function completely now, it was being used for the first implementation I suggested.

2024-09-05 14:19 UTC, ybidois commented
@oyo any clue when this will be merged? It really makes the service marketplace look bad 😂

2024-09-17 11:31 UTC, oyo approved these changes

2024-09-17 11:31 UTC, merged

2024-09-17 11:31 UTC, oyo commented
> @oyo any clue when this will be merged? It really makes the service marketplace look bad 😂

@ybidois done :)